#!/bin/sh
npm run --prefix ./terraform/modules/sslchecker/modules/sslminion/src build
npm run --prefix ./terraform/modules/sslchecker/modules/sslminion/src add
npm run --prefix ./terraform/modules/sslchecker/modules/sslminion/src echo